use_frozen_background: true
use_open_data: false
data_source: frozen

regions:
  - Europe
  - America
  - Oceania
  - Asia
  - Africa

samples:
  Europe: 200
  America: 300
  Oceania: 50
  Asia: 300
  Africa: 400

genes:
  - "N"
  - E
  - M
  - ORF1a
  - ORF1b
  - ORF3a
  - ORF6
  - ORF7a
  - ORF7b
  - ORF8
  - ORF9b
  - S
